margin = 88
whitespace_typedefs = true
whitespace_ops_in_indices = false
remove_extra_newlines = true
short_to_long_function_def = true
long_to_short_function_def = true
annotate_untyped_fields_with_any = true
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = true
indent_submodule = true
separate_kwargs_with_semicolon = true
